{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orphaned-user-resolver.fullname" . }}
type: Opaque
data:
  SERVER_IP: {{ .Values.settings.SERVER_IP | b64enc | quote }}
  SA_USER: {{ .Values.settings.SA_USER | b64enc | quote }}
  SA_PASSWORD: {{ .Values.settings.SA_PASSWORD | b64enc | quote }}
{{- end }}
